spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.238.1.230:3306/polymorph?serverTimezone=Asia/Seoul
    username: test
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    spring.jpa.defer-datasource-initialization: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  token-name: poly-token
  secret: bXktcHJvamVjdC1uYW1lLXBvbHltb3JwaC1hbmQtdGhpcy1pcy1qd3QtYXV0aGVudGljYXRpb24tc2VjcmV0LWtleS1mb3ItSFM1MTItc2lnbldpdGg=
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000

test:
  email: qwejklasd@naver.com

server:
  port: 8000

kakao:
  client-id: ${kakao.clientId}
  redirect-uri: ${kakao.redirectURI}

github:
  client-id: ${github.clientId}
  client-secret: ${github.clientSecret}